# ============================================================================
#
# The configuration produced by default is meant to highlight the features
# that Zensical provides and to serve as a starting point for your own
# projects.
#
# ============================================================================

[project]

site_name = "mlforlife"
site_description = "Prepare for your AI/ML Interviews together."
site_author = "Harish Gehlot"
copyright = "&copy; 2026 Harish Gehlot"

extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
]
[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.theme.icon]
logo = "lucide/gpu"

nav = [
  {"Get Started" = "index.md"},
  {"1.Basics" = ["1 Basics/PythonEssentials.md", "Basics/OopsDbms.md"]},
  {"ML Algorithms" = ["2 Algorithms/LinearRegression.md",
   "2 Algorithms/LogisticRegression.md",
    "2 Algorithms/SupportVectorMachine.md",
    "2 Algorithms/DecisionTree.md",
    "2 Algorithms/RandomForests.md",
    "2 Algorithms/XGBoost.md"]}, 
]

[[project.extra.social]]
icon = "fontawesome/solid/paper-plane"
link = "mailto:gehloth03@gmail.com"
name = "Drop me a Mail"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/Hg03"
name = "Github Repo"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://linkedin.com/in/harishgehlot"
name = "LinkedIn"

[project.markdown_extensions]
footnotes = {}

[project.theme]
features = [
    "content.footnote.tooltips",
    "content.code.copy"
]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]

[[project.theme.palette]] 
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
